# Mac OS X uses path_helper and /etc/paths.d to preload PATH, clear it out first
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

# unique path
typeset -gU PATH path

BREW_PREFIX="$(command -v brew > /dev/null 2>&1 && brew --prefix)"

# brew
if [ -n "$BREW_PREFIX" ]
then
    export PATH="$BREW_PREFIX/bin:$BREW_PREFIX/sbin:$PATH"

    # nvm brew
    if [ -L "$BREW_PREFIX/opt/nvm" ]; then
        export NVM_DIR=~/.nvm
        source "$BREW_PREFIX/opt/nvm/nvm.sh"
    fi

    # go brew
    if [ -L "$BREW_PREFIX/opt/go" ]; then
        export PATH="$BREW_PREFIX/opt/go/libexec/bin:$PATH"
    fi
else
    # nvm on linux
    if [ -z "$NVM_DIR" ] && [ -s "$HOME/.nvm/nvm.sh" ]; then
        export NVM_DIR=~/.nvm
        source "$NVM_DIR/nvm.sh"
    fi
fi

# go path
if [ -d "$HOME/Git/go" ]; then
    export GOPATH="$HOME/Git/go"
    export PATH="$GOPATH/bin:$PATH"
fi

# dotfiles overrides
export PATH="$DOTFILES/bin:$PATH"
