# unique path
typeset -gU PATH path

# Mac OS X uses path_helper and /etc/paths.d to preload PATH, clear it out first
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

# homebrew
if [ -x "$(command -v brew)" ]; then
    export PATH="$(brew --prefix)/bin:$PATH"
    export PATH="$(brew --prefix)/sbin:$PATH"
fi

# anaconda
if [ -d "$HOME/anaconda/bin" ]; then
    export PATH="$PATH:$HOME/anaconda/bin"
fi

# rust
if [ -d "$HOME/.cargo/bin" ]; then
    export PATH="$HOME/.cargo/bin:$PATH"
fi

# google cloud
if [ -s "$HOME/google-cloud-sdk/path.zsh.inc" ]; then
    source "$HOME/google-cloud-sdk/path.zsh.inc"
fi

# brew
if [ -x "$(command -v brew)" ]
then
    # nvm brew
    if [ -d "$(brew --prefix nvm)" ]; then
        export NVM_DIR=~/.nvm
        source "$(brew --prefix nvm)/nvm.sh"
    fi

    # go brew
    if [ -d "$(brew --prefix go)" ]; then
        export PATH="$(brew --prefix go)/libexec/bin:$PATH"
    fi
else
    # nvm on linux
    if [ -z "$NVM_DIR" ] && [ -s "$HOME/.nvm/nvm.sh" ]; then
        export NVM_DIR=~/.nvm
        source "$NVM_DIR/nvm.sh"
    fi
fi

# go path
if [ -x "$(command -v go)" ]; then
    export GOPATH="$HOME/Git/go"
    export PATH="$GOPATH/bin:$PATH"
fi

# dotfiles overrides
export PATH="$DOTFILES/bin:$PATH"
